<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Plandiet\App\Tools\RuleEditor\Enums\NutritionRuleConstraintTypeEnum;
use Plandiet\App\Tools\RuleEditor\Enums\NutritionRulePriorityEnum;
use Plandiet\App\Tools\RuleEditor\Models\NutritionRule;
use Plandiet\App\Tools\RuleEditor\Models\RuleTemplate;
use Plandiet\Infrastructure\Enums\OperatorEnum;

/**
 * NutritionRuleSeeder
 *
 * Seeds nutrition rules for all 127 clients generated by ClientSeeder.
 * Rules are derived from each client's conditions, allergies, and
 * intolerances using the same template names from RuleTemplateSeeder.
 *
 * Available templates (from RuleTemplateSeeder):
 *
 *   T2DM:
 *     'Diabetes + weight loss: tighter carb limit'    (carbs_g ≤ 40, hard, high)
 *     'Diabetes: low glycaemic index preference'       (gi ≤ 55, soft, medium)
 *
 *   Hypertension:
 *     'Hypertension: sodium limit per meal'            (sodium_mg ≤ 600, hard, high)
 *     'Hypertension: daily sodium ceiling'             (sodium_mg_daily ≤ 1500, hard, critical)
 *     'Hypertension: potassium-rich foods boost'       (potassium, soft, medium)
 *
 *   Hypercholesterolaemia:
 *     'High cholesterol: saturated fat daily limit'    (sat_fat_g ≤ 15, hard, high)
 *     'High cholesterol: fibre target'                 (fibre_g ≥ 30, soft, medium)
 *
 *   CKD:
 *     'CKD: phosphorus limit'                          (phosphorus_mg ≤ 800, hard, high)
 *     'CKD: protein restriction'                       (protein_g ≤ 60, hard, high)
 *
 *   Allergens (manual — no template):
 *     tree_nuts EXCLUDE critical
 *     peanuts   EXCLUDE critical
 *     shellfish EXCLUDE critical
 *     fish      EXCLUDE high
 *     eggs      EXCLUDE high
 *     gluten    EXCLUDE high
 *     sesame    EXCLUDE high
 *
 *   Intolerances:
 *     dairy EXCLUDE high
 *     gluten EXCLUDE high (if intolerance and not already allergen)
 *     lactose EXCLUDE high
 *
 *   Dietary preferences:
 *     halal   REQUIRE critical
 *     vegan   REQUIRE high  + dairy/eggs/fish EXCLUDE
 *     kosher  REQUIRE high
 *     vegetarian REQUIRE medium
 */
class NutritionRuleSeeder extends Seeder
{
    private string $exclude;
    private string $require;
    private string $hard;
    private string $soft;
    private string $critical;
    private string $high;
    private string $medium;

    public function run(): void
    {
        $this->exclude  = OperatorEnum::EXCLUDE->value;
        $this->require  = OperatorEnum::REQUIRE->value;
        $this->hard     = NutritionRuleConstraintTypeEnum::HARD->value;
        $this->soft     = NutritionRuleConstraintTypeEnum::SOFT->value;
        $this->critical = NutritionRulePriorityEnum::CRITICAL->value;
        $this->high     = NutritionRulePriorityEnum::HIGH->value;
        $this->medium   = NutritionRulePriorityEnum::MEDIUM->value;

        $sarah = User::where('email', 'sarah@plandiet.com')->first();
        $amir  = User::where('email', 'amir@plandiet.com')->first();

        // ── All 127 clients with their practitioners ──────────────────────────
        $clients = $this->clientRuleMap($sarah, $amir);

        foreach ($clients as $config) {
            $client      = User::where('email', $config['email'])->first();
            $practitioner = $config['practitioner'];
            if (!$client || !$practitioner) {
                continue;
            }
            $this->applyRules($client, $practitioner, $config);
        }
    }

    // ─── Rule application ──────────────────────────────────────────────────────

    private function applyRules(User $client, User $practitioner, array $config): void
    {
        $conditions  = $config['conditions']  ?? [];
        $allergies   = $config['allergies']   ?? [];
        $intolerances = $config['intolerances'] ?? [];
        $dietary     = $config['dietary']     ?? [];
        $overrides   = $config['overrides']   ?? [];

        // ── Condition-based templates ──────────────────────────────────────────

        // T2DM
        if (in_array('diabetes_t2', $conditions)) {
            $carbOverride = $overrides['carb_limit'] ?? [];
            // Tighter carb limit for weight-loss goal; default 40g if goal is weight-related
            $this->createFromTemplate(
                'Diabetes + weight loss: tighter carb limit',
                $client, $practitioner,
                array_merge(['value' => 40], $carbOverride)
            );
            $this->createFromTemplate(
                'Diabetes: low glycaemic index preference',
                $client, $practitioner
            );
        }

        // Hypertension
        if (in_array('hypertension', $conditions)) {
            $sodiumOverride = $overrides['sodium_meal'] ?? [];
            $this->createFromTemplate(
                'Hypertension: sodium limit per meal',
                $client, $practitioner,
                array_merge(['value' => 600], $sodiumOverride)
            );
            $this->createFromTemplate(
                'Hypertension: daily sodium ceiling',
                $client, $practitioner
            );
            $this->createFromTemplate(
                'Hypertension: potassium-rich foods boost',
                $client, $practitioner
            );
        }

        // Hypercholesterolaemia
        if (in_array('hypercholesterolaemia', $conditions)) {
            $this->createFromTemplate(
                'High cholesterol: saturated fat daily limit',
                $client, $practitioner
            );
            $this->createFromTemplate(
                'High cholesterol: fibre target',
                $client, $practitioner
            );
        }

        // CKD
        if (in_array('ckd', $conditions)) {
            $proteinOverride = $overrides['protein_limit'] ?? [];
            $this->createFromTemplate(
                'CKD: phosphorus limit',
                $client, $practitioner
            );
            $this->createFromTemplate(
                'CKD: protein restriction',
                $client, $practitioner,
                array_merge(['value' => 50], $proteinOverride)
            );
        }

        // ── Allergen exclusions (hard, critical) ───────────────────────────────
        $allergenPriority = [
            'nuts'       => $this->critical,
            'tree_nuts'  => $this->critical,
            'peanuts'    => $this->critical,
            'shellfish'  => $this->critical,
            'fish'       => $this->high,
            'eggs'       => $this->high,
            'gluten'     => $this->high,
            'sesame'     => $this->high,
        ];

        foreach ($allergies as $allergen) {
            $allergenKey = $allergen === 'nuts' ? 'tree_nuts' : $allergen;
            $priority    = $allergenPriority[$allergenKey] ?? $this->high;
            $this->createExcludeRule(
                $client, $practitioner,
                $allergenKey,
                "Allergy: exclude {$allergenKey}",
                $this->hard,
                $priority
            );
        }

        // ── Intolerance exclusions (hard, high) ────────────────────────────────
        foreach ($intolerances as $intolerance) {
            $nutrient = $intolerance === 'lactose' ? 'dairy' : $intolerance;
            // Skip if already added as allergen
            if (!in_array($nutrient, array_map(
                fn ($a) => $a === 'nuts' ? 'tree_nuts' : $a, $allergies
            ))) {
                $this->createExcludeRule(
                    $client, $practitioner,
                    $nutrient,
                    "Intolerance: exclude {$nutrient}",
                    $this->hard,
                    $this->high
                );
            }
        }

        // ── Dietary preferences ────────────────────────────────────────────────
        foreach ($dietary as $pref) {
            switch ($pref) {
                case 'halal':
                    $this->createRequireRule($client, $practitioner, 'halal', 'Halal: require halal ingredients', $this->critical);
                    $this->createExcludeRule($client, $practitioner, 'pork', 'Halal: exclude pork', $this->hard, $this->critical);
                    $this->createExcludeRule($client, $practitioner, 'alcohol', 'Halal: exclude alcohol', $this->hard, $this->critical);
                    break;

                case 'vegan':
                    $this->createRequireRule($client, $practitioner, 'vegan', 'Vegan: require plant-based only', $this->high);
                    // Exclude animal products not already excluded
                    foreach (['dairy', 'eggs', 'fish', 'meat', 'shellfish'] as $product) {
                        if (!in_array($product, $allergies) && !in_array($product, $intolerances)) {
                            $this->createExcludeRule($client, $practitioner, $product, "Vegan: exclude {$product}", $this->hard, $this->high);
                        }
                    }
                    break;

                case 'vegetarian':
                    $this->createRequireRule($client, $practitioner, 'vegetarian', 'Vegetarian: no meat or fish', $this->medium);
                    foreach (['meat', 'fish', 'shellfish'] as $product) {
                        if (!in_array($product, $allergies)) {
                            $this->createExcludeRule($client, $practitioner, $product, "Vegetarian: exclude {$product}", $this->hard, $this->medium);
                        }
                    }
                    break;

                case 'kosher':
                    $this->createRequireRule($client, $practitioner, 'kosher', 'Kosher: require kosher certified', $this->high);
                    $this->createExcludeRule($client, $practitioner, 'pork', 'Kosher: exclude pork', $this->hard, $this->critical);
                    $this->createExcludeRule($client, $practitioner, 'shellfish', 'Kosher: exclude shellfish', $this->hard, $this->critical);
                    break;
            }
        }
    }

    // ─── Helpers ───────────────────────────────────────────────────────────────

    private function createFromTemplate(
        string $templateName,
        User   $client,
        User   $practitioner,
        array  $overrides = []
    ): void {
        $template = RuleTemplate::where('name', $templateName)->first();
        if (!$template) {
            return;
        }

        NutritionRule::firstOrCreate(
            ['client_id' => $client->id, 'name' => $template->name],
            array_merge([
                'client_id'        => $client->id,
                'practitioner_id'  => $practitioner->id,
                'rule_template_id' => $template->id,
                'name'             => $template->name,
                'nutrient'         => $template->nutrient,
                'operator'         => $template->operator,
                'value'            => $template->default_value,
                'unit'             => $template->unit,
                'constraint_type'  => $template->constraint_type,
                'priority'         => $template->priority,
                'applies_when'     => json_encode(['meal_type' => 'all']),
                'is_active'        => true,
                'version'          => 1,
            ], $overrides)
        );
    }

    private function createExcludeRule(
        User   $client,
        User   $practitioner,
        string $nutrient,
        string $name,
        string $constraintType,
        string $priority
    ): void {
        NutritionRule::firstOrCreate(
            ['client_id' => $client->id, 'name' => $name],
            [
                'client_id'       => $client->id,
                'practitioner_id' => $practitioner->id,
                'name'            => $name,
                'nutrient'        => $nutrient,
                'operator'        => $this->exclude,
                'value'           => null,
                'unit'            => null,
                'constraint_type' => $constraintType,
                'priority'        => $priority,
                'applies_when'    => json_encode(['meal_type' => 'all']),
                'is_active'       => true,
                'version'         => 1,
            ]
        );
    }

    private function createRequireRule(
        User   $client,
        User   $practitioner,
        string $nutrient,
        string $name,
        string $priority
    ): void {
        NutritionRule::firstOrCreate(
            ['client_id' => $client->id, 'name' => $name],
            [
                'client_id'       => $client->id,
                'practitioner_id' => $practitioner->id,
                'name'            => $name,
                'nutrient'        => $nutrient,
                'operator'        => $this->require,
                'value'           => null,
                'unit'            => null,
                'constraint_type' => $this->hard,
                'priority'        => $priority,
                'applies_when'    => json_encode(['meal_type' => 'all']),
                'is_active'       => true,
                'version'         => 1,
            ]
        );
    }

    // ─── Client → rule config map (all 127 clients) ───────────────────────────

    private function clientRuleMap(?User $sarah, ?User $amir): array
    {
        return [

            // ══════════════════════════════════════════════════════════════════
            // ORIGINAL 3
            // ══════════════════════════════════════════════════════════════════
            [
                'email' => 'fatima@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2'], 'allergies' => ['nuts', 'peanuts'],
                'intolerances' => [], 'dietary' => ['halal'],
                'overrides' => ['carb_limit' => ['value' => 40, 'practitioner_note' => 'Fatima on weight-loss goal, tighter carb ceiling per NHS Q2 guidance.']],
            ],
            [
                'email' => 'marcus@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension', 'hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 550, 'practitioner_note' => 'Marcus on ramipril — keeping sodium lower than default template.']],
            ],
            [
                'email' => 'lin@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ckd'], 'allergies' => ['shellfish'],
                'intolerances' => ['lactose'], 'dietary' => [],
                'overrides' => ['protein_limit' => ['value' => 50, 'practitioner_note' => 'Lin stage 3 CKD, non-dialysis. Strict protein control essential.']],
            ],

            // ══════════════════════════════════════════════════════════════════
            // TYPE 2 DIABETES
            // ══════════════════════════════════════════════════════════════════
            [
                'email' => 'priya.sharma@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2'], 'allergies' => [],
                'intolerances' => ['lactose'], 'dietary' => ['vegetarian'],
            ],
            [
                'email' => 'david.okafor@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2', 'hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 580, 'practitioner_note' => 'Combined T2DM+hypertension — moderate sodium ceiling.']],
            ],
            [
                'email' => 'maria.santos@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2'], 'allergies' => ['fish'],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'james.whitfield@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2', 'hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'aisha.mohammed@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2'], 'allergies' => ['eggs'],
                'intolerances' => [], 'dietary' => ['halal'],
            ],
            [
                'email' => 'robert.chen@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2', 'ckd'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['protein_limit' => ['value' => 55, 'practitioner_note' => 'Dual T2DM+CKD — protein tightly managed.']],
            ],
            [
                'email' => 'sarah.patel@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2'], 'allergies' => ['nuts'],
                'intolerances' => ['gluten'], 'dietary' => ['vegetarian'],
            ],
            [
                'email' => 'thomas.adeyemi@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'claire.dubois@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2', 'hypertension'], 'allergies' => [],
                'intolerances' => ['lactose'], 'dietary' => [],
                'overrides' => [
                    'carb_limit'  => ['value' => 40],
                    'sodium_meal' => ['value' => 560],
                ],
            ],
            [
                'email' => 'ahmed.khalil@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2', 'hypercholesterolaemia'], 'allergies' => ['shellfish'],
                'intolerances' => [], 'dietary' => ['halal'],
            ],
            [
                'email' => 'yuki.tanaka@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'peter.kowalski@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'nadia.rahman@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2'], 'allergies' => ['nuts', 'sesame'],
                'intolerances' => [], 'dietary' => ['halal'],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'carlos.mendez@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2', 'hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 570]],
            ],

            // ══════════════════════════════════════════════════════════════════
            // HYPERTENSION
            // ══════════════════════════════════════════════════════════════════
            [
                'email' => 'patricia.williams@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 580]],
            ],
            [
                'email' => 'emmanuel.asante@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension', 'hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 560, 'practitioner_note' => 'Dual hypertension+cholesterol — lower sodium target.']],
            ],
            [
                'email' => 'helen.papadopoulos@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 550]],
            ],
            [
                'email' => 'michael.osei@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypertension'], 'allergies' => ['peanuts'],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 570]],
            ],
            [
                'email' => 'fatou.diallo@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => ['halal'],
            ],
            [
                'email' => 'derek.thompson@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypertension', 'hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 560]],
            ],
            [
                'email' => 'amara.diop@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension'], 'allergies' => [],
                'intolerances' => ['lactose'], 'dietary' => [],
            ],
            [
                'email' => 'susan.mitchell@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 570]],
            ],
            [
                'email' => 'kwame.mensah@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension', 'diabetes_t2'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'sodium_meal' => ['value' => 540, 'practitioner_note' => 'Dual condition — lower sodium to protect kidneys and BP simultaneously.'],
                    'carb_limit'  => ['value' => 40],
                ],
            ],
            [
                'email' => 'isabelle.laurent@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypertension'], 'allergies' => ['fish'],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'abdul.noor@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension', 'diabetes_t2'], 'allergies' => [],
                'intolerances' => [], 'dietary' => ['halal'],
                'overrides' => [
                    'sodium_meal' => ['value' => 550],
                    'carb_limit'  => ['value' => 40],
                ],
            ],

            // ══════════════════════════════════════════════════════════════════
            // HYPERCHOLESTEROLAEMIA
            // ══════════════════════════════════════════════════════════════════
            [
                'email' => 'olivia.henderson@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'frank.nwosu@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypercholesterolaemia', 'hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 570]],
            ],
            [
                'email' => 'mei.zhang@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'graham.ellis@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'samira.hassan@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypercholesterolaemia'], 'allergies' => ['nuts'],
                'intolerances' => [], 'dietary' => ['halal'],
            ],
            [
                'email' => 'oliver.burke@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypercholesterolaemia', 'diabetes_t2'], 'allergies' => [],
                'intolerances' => ['lactose'], 'dietary' => [],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'nneka.eze@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypercholesterolaemia', 'hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 560]],
            ],

            // ══════════════════════════════════════════════════════════════════
            // CHRONIC KIDNEY DISEASE
            // ══════════════════════════════════════════════════════════════════
            [
                'email' => 'margaret.davies@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ckd'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['protein_limit' => ['value' => 48]],
            ],
            [
                'email' => 'vikram.singh@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ckd', 'hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => ['vegetarian'],
                'overrides' => [
                    'protein_limit' => ['value' => 55],
                    'sodium_meal'   => ['value' => 540, 'practitioner_note' => 'CKD+hypertension — strict sodium management required.'],
                ],
            ],
            [
                'email' => 'brenda.okonkwo@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ckd', 'diabetes_t2'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'protein_limit' => ['value' => 50],
                    'carb_limit'    => ['value' => 40],
                ],
            ],
            [
                'email' => 'hideo.yamamoto@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ckd'], 'allergies' => ['shellfish'],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['protein_limit' => ['value' => 50]],
            ],
            [
                'email' => 'rose.oduya@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ckd', 'hypertension'], 'allergies' => [],
                'intolerances' => ['lactose'], 'dietary' => [],
                'overrides' => [
                    'protein_limit' => ['value' => 48],
                    'sodium_meal'   => ['value' => 500, 'practitioner_note' => 'CKD stage 3b + hypertension — very low sodium target.'],
                ],
            ],
            [
                'email' => 'john.eriksson@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ckd', 'hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['protein_limit' => ['value' => 52]],
            ],
            [
                'email' => 'miriam.okello@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ckd'], 'allergies' => ['eggs'],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['protein_limit' => ['value' => 50]],
            ],

            // ══════════════════════════════════════════════════════════════════
            // IBS / GASTROINTESTINAL
            // ══════════════════════════════════════════════════════════════════
            [
                'email' => 'sophie.tremblay@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs'], 'allergies' => [],
                'intolerances' => ['lactose', 'gluten'], 'dietary' => [],
            ],
            [
                'email' => 'daniel.park@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs'], 'allergies' => [],
                'intolerances' => ['lactose'], 'dietary' => [],
            ],
            [
                'email' => 'harriet.osei@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs'], 'allergies' => [],
                'intolerances' => ['gluten'], 'dietary' => [],
            ],
            [
                'email' => 'leo.fitzgerald@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'amina.toure@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs'], 'allergies' => [],
                'intolerances' => ['lactose'], 'dietary' => ['halal'],
            ],
            [
                'email' => 'william.blackwood@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ibs', 'hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => ['gluten', 'lactose'], 'dietary' => [],
            ],
            [
                'email' => 'chidinma.eze@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs'], 'allergies' => ['eggs'],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'ryan.murphy@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ibs'], 'allergies' => [],
                'intolerances' => ['lactose'], 'dietary' => [],
            ],

            // ══════════════════════════════════════════════════════════════════
            // NUT / PEANUT ALLERGY
            // ══════════════════════════════════════════════════════════════════
            [
                'email' => 'layla.abdullah@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => ['nuts', 'peanuts', 'sesame'],
                'intolerances' => [], 'dietary' => ['halal'],
            ],
            [
                'email' => 'ben.carpenter@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => ['peanuts', 'tree_nuts'],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'zara.ahmed@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2'], 'allergies' => ['peanuts'],
                'intolerances' => [], 'dietary' => ['halal'],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'ellie.boateng@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => ['nuts', 'peanuts'],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'kieran.walsh@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypertension'], 'allergies' => ['nuts'],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 560]],
            ],
            [
                'email' => 'funmilayo.bello@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => ['peanuts', 'shellfish'],
                'intolerances' => [], 'dietary' => [],
            ],

            // ══════════════════════════════════════════════════════════════════
            // GLUTEN INTOLERANCE / COELIAC
            // ══════════════════════════════════════════════════════════════════
            [
                'email' => 'caitlin.obrien@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => ['gluten'],
                'intolerances' => ['gluten'], 'dietary' => [],
            ],
            [
                'email' => 'tobias.neumann@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2'], 'allergies' => ['gluten'],
                'intolerances' => ['gluten'], 'dietary' => [],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'adaeze.nwachukwu@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs'], 'allergies' => ['gluten'],
                'intolerances' => ['gluten', 'lactose'], 'dietary' => [],
            ],
            [
                'email' => 'jack.morrison@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypercholesterolaemia'], 'allergies' => ['gluten'],
                'intolerances' => ['gluten'], 'dietary' => [],
            ],
            [
                'email' => 'blessing.chukwu@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => ['gluten'],
                'intolerances' => ['gluten'], 'dietary' => [],
            ],

            // ══════════════════════════════════════════════════════════════════
            // VEGAN / PLANT-BASED
            // ══════════════════════════════════════════════════════════════════
            [
                'email' => 'jade.thompson@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => ['vegan'],
            ],
            [
                'email' => 'kofi.agyemang@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => ['vegan'],
                'overrides' => ['sodium_meal' => ['value' => 560]],
            ],
            [
                'email' => 'anya.petrov@plandiet.com', 'practitioner' => $amir,
                'conditions' => [], 'allergies' => ['nuts'],
                'intolerances' => [], 'dietary' => ['vegan'],
            ],
            [
                'email' => 'abiola.adeyemi@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2'], 'allergies' => [],
                'intolerances' => [], 'dietary' => ['vegan'],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],

            // ══════════════════════════════════════════════════════════════════
            // WEIGHT MANAGEMENT / GENERAL HEALTH
            // ══════════════════════════════════════════════════════════════════
            [
                'email' => 'natasha.ivanova@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'chukwuemeka.ojo@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'ingrid.larsson@plandiet.com', 'practitioner' => $amir,
                'conditions' => [], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'nnamdi.chukwu@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'esme.fontaine@plandiet.com', 'practitioner' => $amir,
                'conditions' => [], 'allergies' => [],
                'intolerances' => ['lactose'], 'dietary' => [],
            ],
            [
                'email' => 'ibrahim.alfarsi@plandiet.com', 'practitioner' => $amir,
                'conditions' => [], 'allergies' => [],
                'intolerances' => [], 'dietary' => ['halal'],
            ],
            [
                'email' => 'patience.kwarteng@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'tom.higgins@plandiet.com', 'practitioner' => $amir,
                'conditions' => [], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'zainab.idris@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => [],
                'intolerances' => [], 'dietary' => ['halal'],
            ],
            [
                'email' => 'caleb.osei@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],

            // ══════════════════════════════════════════════════════════════════
            // COMPLEX / MULTI-COMORBIDITY
            // ══════════════════════════════════════════════════════════════════
            [
                'email' => 'elizabeth.chambers@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2', 'hypertension', 'hypercholesterolaemia'],
                'allergies' => [], 'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'carb_limit'  => ['value' => 40, 'practitioner_note' => 'Triple comorbidity — tight carb control.'],
                    'sodium_meal' => ['value' => 530, 'practitioner_note' => 'Triple comorbidity — strict sodium ceiling.'],
                ],
            ],
            [
                'email' => 'babajide.adebayo@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2', 'hypertension', 'ckd'],
                'allergies' => [], 'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'carb_limit'    => ['value' => 40],
                    'sodium_meal'   => ['value' => 500, 'practitioner_note' => 'CKD+HTN+T2DM — lowest sodium target in caseload.'],
                    'protein_limit' => ['value' => 52],
                ],
            ],
            [
                'email' => 'florence.addo@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypertension', 'ckd', 'hypercholesterolaemia'],
                'allergies' => [], 'intolerances' => ['lactose'], 'dietary' => [],
                'overrides' => [
                    'sodium_meal'   => ['value' => 510],
                    'protein_limit' => ['value' => 50],
                ],
            ],
            [
                'email' => 'harold.winterbottom@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2', 'ckd', 'hypercholesterolaemia'],
                'allergies' => [], 'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'carb_limit'    => ['value' => 40],
                    'protein_limit' => ['value' => 50],
                ],
            ],
            [
                'email' => 'amara.kone@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension', 'hypercholesterolaemia'],
                'allergies' => ['shellfish'], 'intolerances' => [], 'dietary' => ['halal'],
                'overrides' => ['sodium_meal' => ['value' => 550]],
            ],
            [
                'email' => 'rebecca.nartey@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2', 'hypertension'],
                'allergies' => ['nuts', 'eggs'], 'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'carb_limit'  => ['value' => 40],
                    'sodium_meal' => ['value' => 550],
                ],
            ],
            [
                'email' => 'segun.adeleke@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2', 'hypercholesterolaemia'],
                'allergies' => [], 'intolerances' => [], 'dietary' => [],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'cecilia.nkosi@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypertension', 'diabetes_t2'],
                'allergies' => [], 'intolerances' => ['gluten'], 'dietary' => [],
                'overrides' => [
                    'carb_limit'  => ['value' => 40],
                    'sodium_meal' => ['value' => 550],
                ],
            ],
            [
                'email' => 'emmanuel.owusu@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ckd', 'diabetes_t2', 'hypertension'],
                'allergies' => [], 'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'carb_limit'    => ['value' => 40],
                    'sodium_meal'   => ['value' => 480, 'practitioner_note' => 'Triple comorbidity with CKD — most restrictive sodium in caseload.'],
                    'protein_limit' => ['value' => 50],
                ],
            ],
            [
                'email' => 'adwoa.asare@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs', 'hypertension'],
                'allergies' => ['nuts'], 'intolerances' => ['lactose'], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 560]],
            ],
            [
                'email' => 'joseph.asante@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2', 'ibs'],
                'allergies' => [], 'intolerances' => ['gluten'], 'dietary' => [],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'abena.ofori@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypercholesterolaemia'],
                'allergies' => ['shellfish', 'fish'], 'intolerances' => [], 'dietary' => [],
            ],

            // ══════════════════════════════════════════════════════════════════
            // ADDITIONAL DIVERSITY CLIENTS
            // ══════════════════════════════════════════════════════════════════
            [
                'email' => 'kolade.babatunde@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 570]],
            ],
            [
                'email' => 'amaka.ezeji@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2'], 'allergies' => ['peanuts'],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'mustafa.ozturk@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypertension', 'diabetes_t2'], 'allergies' => [],
                'intolerances' => [], 'dietary' => ['halal'],
                'overrides' => [
                    'sodium_meal' => ['value' => 550],
                    'carb_limit'  => ['value' => 40],
                ],
            ],
            [
                'email' => 'iyabo.balogun@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypercholesterolaemia', 'diabetes_t2'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'hamish.macleod@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypertension', 'hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 560]],
            ],
            [
                'email' => 'sade.afolabi@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs'], 'allergies' => ['gluten'],
                'intolerances' => ['gluten', 'lactose'], 'dietary' => [],
            ],
            [
                'email' => 'kweku.antwi@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2', 'hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'carb_limit'  => ['value' => 40],
                    'sodium_meal' => ['value' => 550],
                ],
            ],
            [
                'email' => 'charity.mensah@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => ['eggs', 'nuts'],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'osei.bonsu@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'abigail.oppong@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2'], 'allergies' => [],
                'intolerances' => ['lactose'], 'dietary' => [],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'akua.nyarko@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension', 'ckd'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'sodium_meal'   => ['value' => 520],
                    'protein_limit' => ['value' => 50],
                ],
            ],
            [
                'email' => 'yaw.amponsah@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2', 'hypertension', 'ckd'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'carb_limit'    => ['value' => 40],
                    'sodium_meal'   => ['value' => 490],
                    'protein_limit' => ['value' => 50],
                ],
            ],
            [
                'email' => 'comfort.darkwah@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs', 'hypercholesterolaemia'], 'allergies' => ['nuts'],
                'intolerances' => ['lactose'], 'dietary' => [],
            ],
            [
                'email' => 'samuel.owiredu@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ckd', 'hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['protein_limit' => ['value' => 52]],
            ],
            [
                'email' => 'theodora.amponsah@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => ['shellfish', 'fish'],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'kwabena.twumasi@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension', 'diabetes_t2'], 'allergies' => [],
                'intolerances' => ['lactose'], 'dietary' => [],
                'overrides' => [
                    'carb_limit'  => ['value' => 40],
                    'sodium_meal' => ['value' => 550],
                ],
            ],
            [
                'email' => 'mavis.darko@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypercholesterolaemia', 'hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 555]],
            ],
            [
                'email' => 'nana.boateng@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => ['peanuts'],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'kwasi.prempeh@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2', 'ckd'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'carb_limit'    => ['value' => 40],
                    'protein_limit' => ['value' => 50],
                ],
            ],
            [
                'email' => 'esi.boateng@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs'], 'allergies' => ['eggs'],
                'intolerances' => ['lactose'], 'dietary' => [],
            ],
            [
                'email' => 'anthony.acheampong@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 570]],
            ],
            [
                'email' => 'grace.asante@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2', 'hypertension', 'hypercholesterolaemia'],
                'allergies' => [], 'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'carb_limit'  => ['value' => 40],
                    'sodium_meal' => ['value' => 530, 'practitioner_note' => 'Triple comorbidity — strict sodium target.'],
                ],
            ],
            [
                'email' => 'philip.mensah@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => ['nuts', 'fish'],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'perpetua.agyapong@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypercholesterolaemia'], 'allergies' => ['shellfish'],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'victor.amoah@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'abena.ankomah@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => ['peanuts', 'tree_nuts', 'sesame'],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'kofi.boateng@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypertension', 'diabetes_t2'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'carb_limit'  => ['value' => 40],
                    'sodium_meal' => ['value' => 550],
                ],
            ],
            [
                'email' => 'eunice.asiedu@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs', 'diabetes_t2'], 'allergies' => [],
                'intolerances' => ['lactose', 'gluten'], 'dietary' => [],
                'overrides' => ['carb_limit' => ['value' => 40]],
            ],
            [
                'email' => 'james.gyamfi@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ckd', 'hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'sodium_meal'   => ['value' => 500],
                    'protein_limit' => ['value' => 49],
                ],
            ],
            [
                'email' => 'cynthia.owusu@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypercholesterolaemia', 'hypertension'], 'allergies' => ['eggs'],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 555]],
            ],
            [
                'email' => 'nana.yeboah@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['diabetes_t2', 'hypertension', 'ckd'],
                'allergies' => [], 'intolerances' => ['lactose'], 'dietary' => [],
                'overrides' => [
                    'carb_limit'    => ['value' => 40],
                    'sodium_meal'   => ['value' => 480, 'practitioner_note' => 'Elderly patient — triple comorbidity, conservative targets throughout.'],
                    'protein_limit' => ['value' => 50],
                ],
            ],
            [
                'email' => 'dorcas.adomako@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => ['nuts', 'peanuts', 'sesame'],
                'intolerances' => ['gluten'], 'dietary' => [],
            ],
            [
                'email' => 'kingsley.frimpong@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 570]],
            ],
            [
                'email' => 'josephine.bonsu@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['ckd', 'diabetes_t2'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'carb_limit'    => ['value' => 40],
                    'protein_limit' => ['value' => 50],
                ],
            ],
            [
                'email' => 'daniel.appiagyei@plandiet.com', 'practitioner' => $sarah,
                'conditions' => [], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
            [
                'email' => 'mary.asanteboateng@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypertension', 'hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => ['lactose'], 'dietary' => [],
                'overrides' => ['sodium_meal' => ['value' => 555]],
            ],
            [
                'email' => 'stephen.tetteh@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['diabetes_t2', 'hypertension'], 'allergies' => ['peanuts'],
                'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'carb_limit'  => ['value' => 40],
                    'sodium_meal' => ['value' => 550],
                ],
            ],
            [
                'email' => 'akosua.ampadu@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['ibs'], 'allergies' => ['shellfish'],
                'intolerances' => ['lactose'], 'dietary' => [],
            ],
            [
                'email' => 'richmond.opoku@plandiet.com', 'practitioner' => $amir,
                'conditions' => ['hypertension', 'ckd'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
                'overrides' => [
                    'sodium_meal'   => ['value' => 510],
                    'protein_limit' => ['value' => 50],
                ],
            ],
            [
                'email' => 'esther.agyei@plandiet.com', 'practitioner' => $sarah,
                'conditions' => ['hypercholesterolaemia'], 'allergies' => [],
                'intolerances' => [], 'dietary' => [],
            ],
        ];
    }
}
