import React, {ReactNode, useState} from "react";

import {Head, Link, router, useForm, usePage} from "@inertiajs/react";
import {Calendar, LayoutDashboard} from "lucide-react";
import {Breadcrumbs} from "@/components/Menu/Breadcrumbs";
import {Crumb, MealPlanItem} from "@/types/types";
import ClientPortalLayout from "@/layouts/Portals/ClientPortalLayout";
import {useToast} from "@/context/ToastContext";
import {getCurrentDateISO, sum} from "@/lib/utils";
import MealHistoryController from "@/actions/App/Http/Controllers/Users/MealHistoryController";
import EmptyState from "@/components/State/EmptyState";
import {isBreakfast, isDinner, isLunch, isSnack} from "@/types/enums";




export default function MealHistoryPage(): ReactNode {

    const { mealHistory } = usePage().props
    const BREADCRUMBS: Crumb[] = [
        { label: "Dashboard", icon: LayoutDashboard },
        { label: "Meal History", icon: Calendar}
    ];


    const toast = useToast()
    const [date, setDate] = useState(getCurrentDateISO)
    const [processing, setProcessing] = useState(false)
    function filterByDate(e: any) {

        let removeStartEventListener = router.on("start", (event) => {
            setProcessing(true)
        });

        let removeFinishEventListener =  router.on("finish", (event) => {
            setProcessing(false)
        });

        console.log(e.target.value)


        router.reload({
            data: {date: e.target.value},

            preserveUrl: true
        })


    }


    return (
        <ClientPortalLayout>
            <Breadcrumbs items={BREADCRUMBS}/>
            <Head title="Meal History" />
            <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                <div>
                    <h2 className="font-serif text-3xl text-emerald-950 sm:text-4xl">
                        Meal History
                    </h2>
                    <p className="mt-1.5 flex items-center gap-1.5 text-sm text-emerald-700/80">
                        View history of meal plans generated by you.
                    </p>
                </div>

            </div>

            <div className="grid lg:grid-cols-3 gap-5">
                <div>
                    <div className="bg-white rounded-2xl border border-sage-100 overflow-hidden mb-4">
                        <div className="px-4 py-3 border-b border-sage-100 flex items-center justify-between">
                            <span className="font-medium text-sage-800 text-sm">Filter by date</span>
                        </div>
                        <div className="p-3">
                            <input value={date} onChange={filterByDate} type="date"  className="w-full rounded-lg border px-3.5 py-2.5 text-sm text-stone-900 outline-none transition-colors focus:border-emerald-600 focus:bg-white focus:ring-2 focus:ring-emerald-600/20" />
                        </div>
                    </div>
                </div>
                <div className="lg:col-span-2">
                    <div className="bg-sage-900 rounded-2xl p-4 grid grid-cols-3 sm:grid-cols-5 gap-3 mb-4 text-center">
                        <div>
                            <div className="font-display text-xl text-sage-300">{sum(mealHistory, "calories").toLocaleString()}</div>
                            <div className="text-xs text-sage-500 uppercase tracking-wider mt-0.5">kcal</div>
                        </div>
                        <div>
                            <div className="font-display text-xl text-sage-300">{sum(mealHistory, "protein_g").toLocaleString()}g</div>
                            <div className="text-xs text-sage-500 uppercase tracking-wider mt-0.5">protein</div>
                        </div>
                        <div>
                            <div className="font-display text-xl text-sage-300">{sum(mealHistory, "carbs_g").toLocaleString()}g</div>
                            <div className="text-xs text-sage-500 uppercase tracking-wider mt-0.5">carbs</div>
                        </div>
                        <div className="hidden sm:block">
                            <div className="font-display text-xl text-sage-300">{sum(mealHistory, "fibre_g").toLocaleString()}g</div>
                            <div className="text-xs text-sage-500 uppercase tracking-wider mt-0.5">fibre</div>
                        </div>
                        <div className="hidden sm:block">
                            <div className="font-display text-xl text-sage-300">{sum(mealHistory, "sodium_mg").toLocaleString()}mg</div>
                            <div className="text-xs text-sage-500 uppercase tracking-wider mt-0.5">sodium</div>
                        </div>
                    </div>
                    <div className="space-y-3">

                        {processing ? (
                            <EmptyState emptyTitle="Loading..." />
                        ) : (
                            <>
                                {mealHistory.length > 0 && (

                                    <>
                                        {mealHistory.map((meal: MealPlanItem) => {
                                            if (isBreakfast(meal.meal_type)) {
                                                return (

                                                    <div
                                                        key={meal.id}
                                                        className="bg-white rounded-2xl border border-sage-100 p-4 flex items-center gap-3 hover-lift">
                                                        <div
                                                            className="w-9 h-9 bg-amber-100 rounded-xl flex items-center justify-center text-lg shrink-0">🌅
                                                        </div>
                                                        <div className="flex-1 min-w-0">
                                                            <div className="text-xs text-sage-400 font-light uppercase tracking-wider">{meal.meal_type}
                                                            </div>
                                                            <div className="text-sm font-medium text-sage-800 truncate">{meal.name}
                                                            </div>
                                                            {meal.was_swapped && (
                                                                <div className="flex gap-1.5 mt-1"><span
                                                                    className="badge bg-purple-100 text-purple-700 text-xs px-2">Swapped</span></div>
                                                            )}
                                                        </div>
                                                        <div className="text-right shrink-0">
                                                            <div className="text-amber-400 text-sm">
                                                                {[...Array(5)].map((_, i) => (
                                                                    <span key={i}>
                                                                         {i < meal.rating ? "★" : "☆"}
                                                                    </span>
                                                                ))}
                                                            </div>
                                                            <div className="text-xs text-sage-400">{meal.rating}/5</div>
                                                        </div>
                                                    </div>
                                                );

                                            }

                                            if(isLunch(meal.meal_type))
                                                return (
                                                    <div
                                                        key={meal.id}
                                                        className="bg-white rounded-2xl border border-sage-100 p-4 flex items-center gap-3 hover-lift">
                                                        <div
                                                            className="w-9 h-9 bg-emerald-100 rounded-xl flex items-center justify-center text-lg shrink-0">☀️
                                                        </div>
                                                        <div className="flex-1 min-w-0">
                                                            <div className="text-xs text-sage-400 font-light uppercase tracking-wider">{meal.meal_type}</div>
                                                            <div className="text-sm font-medium text-sage-800 truncate">{meal.name}
                                                            </div>
                                                            {meal.was_swapped && (
                                                                <div className="flex gap-1.5 mt-1"><span
                                                                    className="badge bg-purple-100 text-purple-700 text-xs px-2">Swapped</span></div>
                                                            )}
                                                        </div>
                                                        <div className="text-right shrink-0">
                                                            <div className="text-amber-400 text-sm">
                                                                <div className="text-amber-400 text-sm">
                                                                    {[...Array(5)].map((_, i) => (
                                                                        <span key={i}>
                                                                         {i < meal.rating ? "★" : "☆"}
                                                                    </span>
                                                                    ))}
                                                                </div>
                                                            </div>
                                                            <div className="text-xs text-sage-400">{meal.rating}/5</div>
                                                        </div>
                                                    </div>
                                                );


                                            if(isSnack(meal.meal_type))
                                                return (
                                                    <div
                                                        key={meal.id}
                                                        className="bg-white rounded-2xl border border-sage-100 p-4 flex items-center gap-3 hover-lift">
                                                        <div
                                                            className="w-9 h-9 bg-blue-100 rounded-xl flex items-center justify-center text-lg shrink-0">🍎
                                                        </div>
                                                        <div className="flex-1 min-w-0">
                                                            <div className="text-xs text-sage-400 font-light uppercase tracking-wider">{meal.meal_type}</div>
                                                            <div className="text-sm font-medium text-sage-800 truncate">{meal.name}
                                                            </div>
                                                            {meal.was_swapped && (
                                                                <div className="flex gap-1.5 mt-1"><span
                                                                    className="badge bg-purple-100 text-purple-700 text-xs px-2">Swapped</span></div>
                                                            )}
                                                        </div>
                                                        <div className="text-right shrink-0">
                                                            <div className="text-amber-400 text-sm">
                                                                {[...Array(5)].map((_, i) => (
                                                                    <span key={i}>
                                                                         {i < meal.rating ? "★" : "☆"}
                                                                    </span>
                                                                ))}
                                                            </div>
                                                            <div className="text-xs text-sage-400">{meal.rating}/5</div>
                                                        </div>
                                                    </div>
                                                );

                                            return (

                                                <div
                                                    key={meal.id}
                                                    className="bg-white rounded-2xl border border-sage-100 p-4 flex items-center gap-3 hover-lift">
                                                    <div
                                                        className="w-9 h-9 bg-blue-100 rounded-xl flex items-center justify-center text-lg flex-shrink-0">🌙
                                                    </div>
                                                    <div className="flex-1 min-w-0">
                                                        <div className="text-xs text-sage-400 font-light uppercase tracking-wider">Dinner</div>
                                                        <div className="text-sm font-medium text-sage-800 truncate">{meal.name}
                                                        </div>
                                                        {meal.was_swapped && (
                                                            <div className="flex gap-1.5 mt-1"><span
                                                                className="badge bg-purple-100 text-purple-700 text-xs px-2">Swapped</span></div>
                                                        )}
                                                    </div>
                                                    <div className="text-right shrink-0">
                                                        <div className="text-amber-400 text-sm">
                                                            {[...Array(5)].map((_, i) => (
                                                                <span key={i}>
                                                                         {i < meal.rating ? "★" : "☆"}
                                                                    </span>
                                                            ))}
                                                        </div>
                                                        <div className="text-xs text-sage-400">{meal.rating}/5</div>
                                                    </div>
                                                </div>
                                            );

                                        })}
                                    </>


                                )}

                                {mealHistory.length == 0 && <div className="bg-white rounded-2xl border border-sage-100 p-4">
                                    <EmptyState emptyTitle="No meals generated on this day"/>
                                </div>}
                            </>
                        )}
                    </div>
                </div>
            </div>


        </ClientPortalLayout>
    );
}
